services:
  - type: web
    name: dstealth-backend
    env: node
    plan: free
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: XMTP_ENV
        value: production
      - key: WALLET_KEY
        fromSecret: WALLET_KEY
      - key: ENCRYPTION_KEY
        fromSecret: ENCRYPTION_KEY
      - key: API_SECRET_KEY
        fromSecret: API_SECRET_KEY
      - key: FRONTEND_URL
        value: https://dstealth.vercel.app
      - key: GROUP_ID
        fromSecret: GROUP_ID
    healthCheckPath: /health
    autoDeploy: true 